package:
  name: py-l8angles
  version: "0.1"

source:
  git_url: https://github.com/Swordman51/py-l8angles-conda
  git_depth: -1

requirements:
  build:
    - python >=3.6
    - cython
    - setuptools
    - numpy

  run:
    - python >=3.6
    - numpy

